# Generated by Django 5.0.2 on 2024-04-15 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0005_remove_databaseattachment_db_delete_database_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم قاعدة البيانات')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='workspace.workspace', verbose_name='بيئة العمل')),
            ],
            options={
                'verbose_name': 'قاعدة بيانات',
                'verbose_name_plural': 'قواعد البيانات',
            },
        ),
        migrations.CreateModel(
            name='DatabaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المرفق ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المرفق')),
                ('file', models.FileField(upload_to='media/db/attachments/', verbose_name='المرفق')),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.database', verbose_name='قاعدة البيانات')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'مرفقات قواعد البيانات',
            },
        ),
    ]
