# Generated by Django 5.0.2 on 2024-04-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'DatabaseType',
                'verbose_name_plural': 'DatabaseTypes',
            },
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نوع الحقل')),
                ('code', models.TextField(verbose_name='الكود')),
                ('db_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.databasetype', verbose_name='نوع قاعدة البيانات')),
            ],
        ),
    ]
