# Generated by Django 5.0.2 on 2024-04-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_databasetype_fieldtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databasetype',
            options={'verbose_name': 'نوع قاعدة بيانات', 'verbose_name_plural': 'أنواع قواعد البيانات'},
        ),
        migrations.AlterModelOptions(
            name='fieldtype',
            options={'verbose_name': 'نوع حقل مسبق', 'verbose_name_plural': 'أنواع الحقول المسبقة'},
        ),
        migrations.CreateModel(
            name='PreBuiltField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحقل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الحقل')),
                ('db_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.databasetype')),
                ('field_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.fieldtype')),
            ],
            options={
                'verbose_name': 'معجم الحقول',
                'verbose_name_plural': 'حقل مسبق',
            },
        ),
    ]
