# Generated by Django 5.0.2 on 2024-04-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_databasetype_options_alter_fieldtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prebuiltfield',
            options={'verbose_name': 'حقل مسبق', 'verbose_name_plural': 'معجم الحقول'},
        ),
        migrations.CreateModel(
            name='DatabaseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحقل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الحقل')),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.database', verbose_name='قاعدة البيانات')),
                ('db_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.databasetype')),
                ('field_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.fieldtype')),
            ],
            options={
                'verbose_name': 'حقل',
                'verbose_name_plural': 'حقول قواعد البيانات ',
            },
        ),
    ]
