# Generated by Django 5.0.2 on 2024-04-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_prebuiltfielddepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebuiltfield',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.prebuiltfielddepartment', verbose_name='القسم'),
        ),
    ]
