# Generated by Django 5.0.2 on 2024-04-16 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_prebuiltfield_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasefield',
            name='db_type',
        ),
        migrations.AddField(
            model_name='database',
            name='db_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.databasetype'),
        ),
    ]
