# Generated by Django 5.0.2 on 2024-04-18 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_databasefield_db_type_database_db_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasefield',
            name='db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='database.database', verbose_name='قاعدة البيانات'),
        ),
    ]
