# Generated by Django 5.0.2 on 2024-03-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitepage',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='الكود'),
        ),
    ]
