# Generated by Django 5.0.2 on 2024-03-31 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_database_databaseattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='workspace.workspace', verbose_name='بيئة العمل'),
        ),
    ]
