# Generated by Django 5.0.2 on 2024-04-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_remove_databaseattachment_db_delete_database_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitepage',
            name='code',
        ),
        migrations.AddField(
            model_name='websitepage',
            name='css',
            field=models.TextField(blank=True, null=True, verbose_name='css'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='html',
            field=models.TextField(blank=True, null=True, verbose_name='html'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='js',
            field=models.TextField(blank=True, null=True, verbose_name='js'),
        ),
    ]
